### ISSUE TITLE
Role too permissive?

### ISSUE THREAD

**Issue by hoerup** [seriohub/velero-helm#4]
in  https://github.com/seriohub/velero-helm/blob/main/seriohub-velero/templates/23_role.yaml theres some resources with 

```
  verbs:
  - '*'

```  
is that really necessary or can they be tightened a bit ?

**Comment by davideserio** [comment]
Hi,
yes, they are 'too permissive' due to some tests in development. 
I believe in the next updates they can be adjusted to the actual permissions required.
