### ISSUE TITLE
velero-ui user password on helm values

### ISSUE THREAD

**Issue by rchekhina** [seriohub/velero-helm#9]
HI David,

is it possible to add the user password on the values.yml ? if it not set on the values.yml auto create a complex password.

Best regards.

**Comment by rchekhina** [comment]
HI David,

I think it will be great to add the user / password on a kubernetes secret because if the pod y recreated it lose the password and set it other time to admin/admin.

Best regards.

**Comment by davideserio** [comment]
Currently, the user data is stored in an SQLite database. If [storage](https://github.com/seriohub/velero-helm/blob/6ced3eb5e2a7403570a91b2e4b61161e1f3c10b9/values-override.yaml#L19) is enabled, a PV and PVC will be created, and the credentials will be retrieved upon recreation.

In the case of not using storage, I need to evaluate the feasibility of including the user and password in the YAML file during installation and/or upgrade.

**Comment by rchekhina** [comment]
HI Davide,

I think it should be better to have it on a kubernetes secret because I have a limitation of pv attached to the kubernetes node.

Best regards

**Comment by rchekhina** [comment]
HI davide,

Ok thank you I will try it.

Best regards.
